### ISSUE TITLE
Statie 3 - a way to get all posts

### ISSUE THREAD

**Issue by TomasVotruba** [crazko/romanvesely.com#32]
I see you load all posts in one bin file:

https://github.com/crazko/romanvesely.com/blob/1172207fd39707ff5ddbda5f6f7849e31c37e1a4/bin/create-note-images#L21

I do the same for Tweets. Before Statie 3.0, there was no better way, but now is.

**For inspiration:**

https://github.com/TomasVotruba/tomasvotruba.cz/blob/d3aa90f47681e0e0a3cc33141596419aae4a5423/src/TweetPublisher/PostsProvider.php#L41-L47

Here is the [upgrading commit](https://github.com/TomasVotruba/tomasvotruba.cz/commit/014d8d6a96264c8d506da435cd724e10db21901e)

**Comment by crazko** [comment]
I haven't known there is version 3, will check it. Thanks for letting know 🍇

**Comment by TomasVotruba** [comment]
Happy to help!

Btw, how do you get updates of releases of your favorite packages?

There is badge to subscribe to releases with link to libraries.io [in README](https://github.com/Symplify/Symplify/blob/master/README.md#symplify-main-repository) in case you don't want to miss next one :) awesome service.

**Comment by crazko** [comment]
I didn't have any process of receiving updates, it wasn't that important for me, be I give it a try :)
