### ISSUE TITLE
error with Statie 4.5

### ISSUE THREAD

**Issue by crazko** [crazko/romanvesely.com#45]
new version produces both error while site compilation and bad output

- https://5b48ee763813f051f29c0376--romanvesely.netlify.com/a-place-to-meet-statie/
- https://travis-ci.org/crazko/romanvesely.com/builds/403676407#L607

One of @Netlify 's strong abilities shows its strength - rollback :)

@TomasVotruba it might be interesting for you ;) but I will look at it myself, just later in the weekend.

**Comment by TomasVotruba** [comment]
It reports bug fixed in dev https://github.com/Symplify/Statie/commit/936a9f5fd015adfb14ecab88630fa0806c66509c

Maybe Statie 4.6-dev is needed

I see there is not test in .travis.yml, there should be generate command at least

**Comment by TomasVotruba** [comment]
Btw, how can I run something like `gulp` in Pehapkari/my web?

I want to see the web with live reaload and I don't get which of those 6 commands is there for it.

So I can see those bugs :)

**Comment by crazko** [comment]
Ok, error was caused by [removed `$layout` variable](https://github.com/crazko/romanvesely.com/pull/44/files#diff-e9eaf83808ae7c7609b3b278ebc9b439L3) in post files. Now its handled in different way.

"Tests" are run by `composer check` script - https://github.com/crazko/romanvesely.com/blob/master/.travis.yml#L16

**Comment by crazko** [comment]
Live reload is described in one of my posts ;) https://romanvesely.com/statie-generate-and-refresh/. As of my site, it's defined here https://github.com/crazko/romanvesely.com/blob/master/gulpfile.js#L105.

In case you need more info, Just tell :palm_tree:

**Comment by TomasVotruba** [comment]
> Maybe Statie 4.6-dev is needed

I though so, the layout is back there for couple of days :).

> In case you need more info, Just tell palm_tree

Just copy-paste command to run it.
